[workspace]
members = ["rapira", "rapira-derive"]
resolver = "3"

[workspace.package]
authors = ["Rail Khusnutdinov <rail@33.run>"]
edition = "2024"

[patch.crates-io]
rapira-derive = { path = "./rapira-derive" }
